### ISSUE TITLE
Catalyst tracking ticket

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#934]
- [x] Battery is always reported as 100% full (UIDevice appears to not work here)
- [x] Background networking sessions seem to always fail and get stuck when the app isn't in the foreground
- [x] Actions: Add to Siri button will say “Shortcuts is unavailable” when clicked, should be hidden.
- [x] Locations: background refresh should be hidden on Mac
- [x] Notifications -> Sounds the imported and system tab should be hidden I think.
- [x] Event Log: when using search/filter if you type something like "test" it will be a white screen. Drilling down/clicking into a Location Update payload on this screen also shows a brief white flash.
- [x] About page, the “Join Beta” and GitHub links are for the iOS version
- [x] Region monitoring is only while the app is running; avoid checking regions on startup and issuing a ton of networking requests for every single region (lol)
- [x] Settings and About don't have shortcuts/menu entries/etc.
- [ ] ~~DeviceKit calls it "iOS Simulator" - project looks dead, probably should just use our own wrapper~~ We call it `x86_64` when we could probably look up a better, full Mac name for it. (This is just what gestalt returns)
- [ ] What does the Battery sensor do on a Mac without a battery?
